name: Feature Request
description: Suggest an idea for this project
title: "[Feat]: "
labels: ["enhancement", "triage"]
assignees:
  - arthurvd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: existing-problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem or missing functionality is.
    validations:
      required: true
  - type: textarea
    id: ideal-solution
    attributes:
      label: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Describe the alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered (if applicable).
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
