name: Task
description: Describe a piece of work (typically non-coding) that should be done.
title: "[Task]: "
labels: ["chore", "triage"]
assignees:
  - arthurvd
body:
  - type: textarea
    id: what-is-the-need
    attributes:
      label: What is the need for this task?
      placeholder: Why should this work be done
    validations:
      required: true
  - type: textarea
    id: what-is-the-task
    attributes:
      label:  What is the task?
      placeholder: A clear and concise description of what you want to be done.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the task here.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
