name: Automated release workflow

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Branch to create release from"
        required: false
        default: "main"
      major:
        description: "The new major version."
        required: false
        type: string
      minor:
        description: "The new minor version."
        required: false
        type: string
      patch:
        description: "The new patch version."
        required: false
        type: string
      increment:
        description: "The type of increment."
        required: false
        type: choice
        options:
          - MAJOR
          - MINOR
          - PATCH
      version:
        description: "Full version to release (e.g. 1.0.0 or 1.0.0-beta.1)"
        required: false
        type: string
      test_mode:
        description: "Run in test mode (no tags or publishing)"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_branch }}

      - name: Determine release version
        id: get_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "Using manual version input: ${{ github.event.inputs.version }}"
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION="${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}"
            echo "Using constructed version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Run image
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.8.4

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.virtualenvs
          key: venv-ubuntu-latest-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Generate changelog
        run: poetry run cz changelog --unreleased-version="${{ github.event.outputs.VERSION }}" --incremental

      - name: Get user info
        id: user_info
        run: |
          USER_JSON=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.actor }}")
          USER_NAME=$(echo "$USER_JSON" | jq -r .name)
          USER_EMAIL=$(echo "$USER_JSON" | jq -r .email)
          echo "::set-output name=name::$USER_NAME"
          echo "::set-output name=email::$USER_EMAIL"

      - name: Configure git
        run: |
          git config --local user.email "${{ steps.user_info.outputs.email }}"
          git config --local user.name "${{ steps.user_info.outputs.name }}"

      - name: Bump version
        run: |
          poetry run cz bump --yes --check-consistency --version ${{ github.event.outputs.VERSION }}
          git push
          git push --tags

      - name: Build hydrolib-core package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ github.event.outputs.VERSION }}
          tag_name: "${{ github.event.outputs.VERSION }}"
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
