name: Test Suite

permissions:
  contents: write


on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install libomp for macos (required by meshkernel)
        if: matrix.os == 'macos-latest'
        run: |
          brew install libomp

      - name: Set up Python with Poetry
        uses: Deltares-research/github-actions/actions/python-setup/poetry@main
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 2.3.3

      - name: Test with pytest
        run: |
          poetry run pytest --cov . --cov-report xml:coverage-reports/coverage-hydrolib-core.xml --junitxml=xunit-reports/xunit-result-hydrolib-core.xml

      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
